### ISSUE TITLE
ReferenceError: Cannot access '__vite_ssr_import_2__' before initialization

### ISSUE THREAD

**Issue by ulrichstark** [tannerlinsley/react-location#5673]
### Which project does this relate to?

Start

### Describe the bug

When starting our tanstack start application in development environment, we sometimes get the following error in the terminal:

```
ReferenceError: Cannot access '__vite_ssr_import_2__' before initialization
    at Module.getRouter (/Users/ulrichstark/Desktop/tanstack-vite-cannot-access-vite-ssr-import-before-initalization/src/router.tsx:7:9)
    ... 2 lines matching cause stack trace ...
    at async eval (/Users/ulrichstark/Desktop/tanstack-vite-cannot-access-vite-ssr-import-before-initalization/node_modules/@tanstack/start-server-core/src/createStartHandler.ts:243:32) {
  cause: ReferenceError: Cannot access '__vite_ssr_import_2__' before initialization
      at Module.getRouter (/Users/ulrichstark/Desktop/tanstack-vite-cannot-access-vite-ssr-import-before-initalization/src/router.tsx:7:9)
      at getRouter (/Users/ulrichstark/Desktop/tanstack-vite-cannot-access-vite-ssr-import-before-initalization/node_modules/@tanstack/start-server-core/src/createStartHandler.ts:123:55)
      at async handleServerRoutes (/Users/ulrichstark/Desktop/tanstack-vite-cannot-access-vite-ssr-import-before-initalization/node_modules/@tanstack/start-server-core/src/createStartHandler.ts:358:18)
      at async eval (/Users/ulrichstark/Desktop/tanstack-vite-cannot-access-vite-ssr-import-before-initalization/node_modules/@tanstack/start-server-core/src/createStartHandler.ts:243:32),
  status: 500,
  statusText: undefined,
  headers: undefined,
  data: undefined,
  body: undefined,
  unhandled: true
}
```

And the opened application in the browser only shows:
```json
{"status":500,"unhandled":true,"message":"HTTPError"}
```

When reloading the page, the error goes away and our application is shown.

### Your Example Website or App

https://github.com/ulrichstark/tanstack-vite-cannot-access-vite-ssr-import-before-initalization

### Steps to Reproduce the Bug or Issue

1. Clone `https://github.com/ulrichstark/tanstack-vite-cannot-access-vite-ssr-import-before-initalization`
2. Go into folder
3. `npm install`
4. Run `npx vite --force`
5. Wait a few seconds
6. If error isn't visible, stop vite and try again starting from step 4

### Expected behavior

No error

### Platform

- Router / Start Version: 1.133.34
- OS: macOS
- Browser: Chrome
- Browser Version: 141.0.7390.123
- Bundler: Vite
- Bundler Version: 7.1.12

### Additional context

Don't mind the funky reproduction project. It's a product of hours deleting stuff in our project to condense it down to the minimal amount of code that triggers this issue. I hope you can reproduce it on your side. I'm not sure what is causing the issue because it seems to be gone when I delete more relevant code from the project. It's most probably something with my `ErrorComponent` and its server function which is used as `defaultErrorComponent`:

```tsx
import { createServerFn } from "@tanstack/react-start";
import { useEffect } from "react";
import { getCookies } from "@tanstack/react-start/server";
import { House } from "lucide-react";

const reportErrorToServer = createServerFn().handler(() => {
    getCookies();
});

export function ErrorComponent() {
    useEffect(() => {
        reportErrorToServer();
    }, []);

    return <House />;
}
```

**Comment by nickwang0808** [comment]
I'm actually stuck with the error and unsure how to get past it

**Comment by ulrichstark** [comment]
> I'm actually stuck with the error and unsure how to get past it

Then it's probably a different issue, because this vite related error is very generic and common and can be the product of a few issues.

**Comment by flodaniel** [comment]
Also facing the same issue. I believe it is due to a circular dependency between `router.tsx` importing `routeTree`, and `routeTree.gen` imports `router.tsx`

router-->routeTree->router

**Comment by kopdigitaal** [comment]
We also have the same issue, any ideas on how to fix this issue?

**Comment by schiller-manuel** [comment]
@flodaniel  @kopdigitaal  do you only have this issue once or does it persist?

**Comment by flodaniel** [comment]
Me and my colleagues have it frequently whenever we start the project initially. It self-resolves, so if we just wait usually at after a minute or so and the project runs.

**Comment by schiller-manuel** [comment]
> whenever we start the project initially

what does this mean? only the first time you run the vite dev server after cloning the repo?

**Comment by flodaniel** [comment]
Sorry no, it happens again and again everytime we start the vite dev server. However from my recollection it does not happen every time but pretty frequently.

**Comment by schiller-manuel** [comment]
@flodaniel would you be able to provide a reproducer for this? the above reproducer only shows this once

**Comment by flodaniel** [comment]
I am working on another repro and will see if it also occurs there.

**Comment by checkerschaf** [comment]
@schiller-manuel I'm getting this error every time I start the dev server **once**.

It happens to me when two calls hit the dev server at the same time and the first one is not finished yet.

This also applies when running my E2E tests locally. That's why I have to make a dummy call to the dev server first, wait ~5 seconds and then start the concurrent tests. It's not a deal breaker but quite annoying to work with.

Unfortunately I don't have time at the moment to create reproducer but I thought these details might help pinpoint the issue.

**Comment by juliomuhlbauer** [comment]
This is happening for me too

**Comment by mackattack3k** [comment]
For me the issue was that in a file with `createServerOnlyFn` I had an import from a `.tsx` component. Not the component itself but merely a type.

I think this caused a circular dependency sure, but also trying to parse tsx as it was in the same file.

**Comment by schiller-manuel** [comment]
@mackattack3k can you show this in a reproducer project?

**Comment by nicksrandall** [comment]
I'm also hitting this error, and I believe it's because we have a circular dependency between router.tsx and routeTree.gen.ts. I'm not certain, though.

**Comment by CarlosZiegler** [comment]
Got same error @schiller-manuel 

<img width="847" height="365" alt="Image" src="https://github.com/user-attachments/assets/61d054a8-b2d5-4901-b26b-87884fa53e8e" />

And this error come in like src/router.tsx:15:3 that is exact line to `routeTree` :

<img width="381" height="162" alt="Image" src="https://github.com/user-attachments/assets/07c28400-2a19-4a06-96a0-38fa472fd8d1" />

I think is related of circular dependency mentioned above from @nicksrandall and @flodaniel

**Comment by Kevinminh** [comment]
Also having this error.

**Comment by moncapitaine** [comment]
I'm experiencing a very similar issue after upgrading from 1.132.6 to 1.140.0.

## Error

```
TypeError: (0 , __vite_ssr_import_10__.useAutomationActions) is not a function
    at Module.AutomationMenu (file:///path/to/app/src/components/automations/automation-menu.tsx:40:62)
```

The dev server crashes completely and requires a restart.

## Versions

- **Working:** `@tanstack/react-router` 1.132.6, `@tanstack/react-start` 1.132.6
- **Broken:** `@tanstack/react-router` 1.140.0, `@tanstack/react-start` 1.140.0

## Pattern

The failing code is a custom hook in a separate file:

```tsx
// automation-menu.tsx
import { useAutomationActions } from './use-automation-actions'

export const AutomationMenu = () => {
  const { deleteAutomation } = useAutomationActions() // crashes here
}
```

```ts
// use-automation-actions.ts
import { useMutation, useQueryClient } from '@tanstack/react-query'
import { useNavigate } from '@tanstack/react-router'

export const useAutomationActions = () => {
  const navigate = useNavigate()
  const queryClient = useQueryClient()
  // ... returns mutation handlers
}
```

## Reproduction context

The issue happens during **E2E tests with Playwright** when multiple concurrent requests hit the dev server. It's intermittent - doesn't happen 100% of the time, but very common under concurrent load.

Reverting to 1.132.6 completely resolves the issue. I've cleared all caches (`node_modules/.vite`, `.vinxi`, turbo cache) and the issue persists with 1.140.0.

## Environment

- OS: Linux (DevContainer)
- Node.js: 22.x
- Vite: 6.x

**Comment by schiller-manuel** [comment]
@moncapitaine  can you share a complete project that reproduces this?

**Comment by amserra** [comment]
Had the same issue. Like @moncapitaine , I was using versions `1.140.0`. With version `1.132.6` it works.

**Comment by schiller-manuel** [comment]
@amserra can you share a complete project that reproduces this?

**Comment by kno-raziel** [comment]
Im also experiencing this issue,

```ts
[vite] connected.
ReferenceError: Cannot access '__vite_ssr_import_6__' before initialization
    at router (rootFolder/packages/app/src/router.tsx:16:22)
    ... 3 lines matching cause stack trace ...
    at async eval (rootFolder/node_modules/.pnpm/@tanstack+start-server-core@1.140.5_c
rossws@0.4.1_srvx@0.9.7_/node_modules/@tanstack/start-server-core/src/createStartHandler.ts:223:34) {
  cause: ReferenceError: Cannot access '__vite_ssr_import_6__' before initialization
      at router (rootFolder/packages/app/src/router.tsx:16:22)
      at getRouter (rootFolder/node_modules/.pnpm/@tanstack+start-server-core@1.140.5_
crossws@0.4.1_srvx@0.9.7_/node_modules/@tanstack/start-server-core/src/createStartHandler.ts:108:57)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async handleServerRoutes (rootFolder/node_modules/.pnpm/@tanstack+start-serve
r-core@1.140.5_crossws@0.4.1_srvx@0.9.7_/node_modules/@tanstack/start-server-core/src/createStartHandler.ts:348:18)
      at async eval (rootFolder/node_modules/.pnpm/@tanstack+start-server-core@1.140.5
_crossws@0.4.1_srvx@0.9.7_/node_modules/@tanstack/start-server-core/src/createStartHandler.ts:223:34),
  status: 500,
  statusText: undefined,
  headers: undefined,
  data: undefined,
  body: undefined,
  unhandled: true
}
```

It happens during the first load of the app. After that I havent seen it.


```
"@tanstack/react-devtools": "^0.8.4",
"@tanstack/react-query": "^5.90.12",
"@tanstack/react-router": "^1.140.5",
"@tanstack/react-router-devtools": "^1.140.5",
"@tanstack/react-router-ssr-query": "^1.140.5",
"@tanstack/react-start": "^1.140.5",
"@tanstack/router-plugin": "^1.140.5",
"@tanstack/zod-adapter": "^1.141.0",
```

**Comment by Flusinerd** [comment]
Maybe this is related. I am getting a similar error when HMR, but its not breaking the dev server:

```
1:51:32 PM [vite] (ssr) page reload src/hooks/use-file-upload.ts
TypeError: (0 , __vite_ssr_import_0__.createStartHandler) is not a function
    at /Users/jan/Dev/m-copilot/frontend/node_modules/@tanstack/react-start/dist/plugin/default-entry/server.ts:8:15
    at ESModulesEvaluator.runInlinedModule (file:///Users/jan/Dev/m-copilot/frontend/node_modules/vite/dist/node/module-runner.js:913:3)
    at ModuleRunner.directRequest (file:///Users/jan/Dev/m-copilot/frontend/node_modules/vite/dist/node/module-runner.js:1146:59)
    at ModuleRunner.cachedRequest (file:///Users/jan/Dev/m-copilot/frontend/node_modules/vite/dist/node/module-runner.js:1053:73)
    at ModuleRunner.import (file:///Users/jan/Dev/m-copilot/frontend/node_modules/vite/dist/node/module-runner.js:1014:10)
    at EnvRunner.reload (file:///Users/jan/Dev/m-copilot/frontend/node_modules/nitro/dist/runtime/internal/vite/dev-worker.mjs:49:20)
    at async Promise.all (index 1)
    at reload (file:///Users/jan/Dev/m-copilot/frontend/node_modules/nitro/dist/runtime/internal/vite/dev-worker.mjs:163:5)
    at MessagePort.<anonymous> (file:///Users/jan/Dev/m-copilot/frontend/node_modules/nitro/dist/runtime/internal/vite/dev-worker.mjs:197:7)
```

```ts
import { defineConfig } from 'vite'
import { tanstackStart } from '@tanstack/react-start/plugin/vite'
import viteReact from '@vitejs/plugin-react'
import viteTsConfigPaths from 'vite-tsconfig-paths'
import tailwindcss from '@tailwindcss/vite'
import { devtools } from '@tanstack/devtools-vite'
import { nitro } from 'nitro/vite'

export default defineConfig({
  plugins: [
    // this is the plugin that enables path aliases
    viteTsConfigPaths({
      projects: ['./tsconfig.json'],
    }),
    devtools(),
    tailwindcss(),
    tanstackStart(),
    viteReact({
      babel: {
        plugins: ['babel-plugin-react-compiler'],
      },
    }),
    nitro(),
  ],
  server: {
    allowedHosts: ['some-domain.local'],
  },
})
```

```
"nitro": "latest",
"@tanstack/match-sorter-utils": "8.19.4",
"@tanstack/react-devtools": "0.8.3",
"@tanstack/react-query": "5.90.12 ",
"@tanstack/react-query-devtools": "5.91.1 ",
"@tanstack/react-router": "1.141.4",
"@tanstack/react-router-devtools": "1.141.4",
"@tanstack/react-router-ssr-query": "1.141.4",
"@tanstack/react-start": "1.141.5",
"@tanstack/react-table": "8.21.3",
"@tanstack/router-plugin": "1.141.5"

"@tanstack/devtools-vite": "0.3.12",
"vite": "7.3.0",
"vitest": "4.0.15",
```

**Comment by nicksrandall** [comment]
## Additional Context: Production Build Issue

We're experiencing a related issue in **production builds** (not just dev) when deploying to Cloud Run with Bun + Nitro. The error manifests on cold starts:

```
ReferenceError: Cannot access 'listEmployees_createServerFn_handler' before initialization
    at getServerFnById (/app/server/chunks/_/server.mjs:8617:18)
```

### Root Cause Analysis

Looking at the bundled output, the issue is a **temporal dead zone (TDZ) error** caused by incorrect variable declaration ordering in the generated code:

```javascript
// In employees.queries-xxx.mjs (bundled output)
const listEmployees_createServerFn_handler = createServerRpc("...", (opts, signal) => listEmployees.__executeServer(opts, signal));
const listEmployees = createServerFn({...}).handler(listEmployees_createServerFn_handler, async (...) => {...});
```

The handler is defined **before** `listEmployees`, but references it in the callback. While the arrow function body isn't evaluated until called, the circular dependency between:
1. `employees.queries` chunk → imports from `server.mjs` (for `createServerRpc`, `createServerFn`)
2. `server.mjs` manifest → dynamically imports `employees.queries` chunk

...causes the export to be accessed before initialization when modules are loaded in a specific order during cold starts.

### Potential Fix Suggestion

The generated code could be restructured to avoid the TDZ issue. Instead of:

```javascript
const handler = createServerRpc("id", (opts, signal) => serverFn.__executeServer(opts, signal));
const serverFn = createServerFn({...}).handler(handler, impl);
```

Consider generating:

```javascript
const serverFn = createServerFn({...}).handler(
  createServerRpc("id", (opts, signal) => serverFn.__executeServer(opts, signal)),
  impl
);
```

Or using a lazy getter pattern that defers the reference until runtime:

```javascript
const handler = createServerRpc("id", (opts, signal) => {
  // Access at call time, not definition time
  return getServerFn("serverFn").__executeServer(opts, signal);
});
```

This would ensure `serverFn` is always defined by the time the callback executes, regardless of module initialization order.

### Environment
- `@tanstack/react-start`: 1.145.3
- Runtime: Bun
- Bundler: Nitro + Vite
- Deployment: Google Cloud Run

**Comment by nicksrandall** [comment]
## Update: Revised Root Cause Analysis

After further investigation, I need to correct my earlier analysis. The handler callback pattern is **NOT** the direct cause of the TDZ error.

### Why the callback pattern isn't the issue

Looking at `createServerRpc`:

```javascript
const createServerRpc = (functionId, splitImportFn) => {
  return Object.assign(splitImportFn, {
    functionId,
    [TSS_SERVER_FUNCTION]: true
  });
};
```

This function simply wraps the callback with metadata using `Object.assign` - it does **not** invoke the callback synchronously. The callback `(opts, signal) => listEmployees.__executeServer(opts, signal)` is just a closure that captures a reference to `listEmployees`. Since `listEmployees` isn't accessed until the callback is actually invoked (at request time), the declaration order shouldn't matter.

### What's actually happening

The error occurs at `getServerFnById` when accessing module exports:

```javascript
const fnModule = await serverFnInfo.importer();  // Dynamic import completes
const action = fnModule[serverFnInfo.functionName];  // TDZ error here!
```

The dynamic import resolves (returns a module namespace object), but accessing the export throws a TDZ error. This means the module is in a partially-initialized state where the `const` declaration hasn't been evaluated yet.

### Likely causes

1. **Circular dependency during module initialization** - The server function chunks import from `server.mjs` AND `index.mjs` (the entry point). If there's a circular reference during cold start, modules could be accessed before fully initialized.

2. **Bun ESM handling** - We're using Bun 1.3.5 + Nitro. There are [known issues with Nitro + Bun ESM resolution](https://github.com/nitrojs/nitro/issues/3185). Bun may be returning from dynamic imports before modules fully execute.

3. **Race condition with concurrent requests** - As @checkerschaf mentioned, this happens "when two calls hit the dev server at the same time and the first one is not finished yet." On cold start, multiple concurrent requests could cause module loading race conditions.

### What we've verified

- Pulled the production Docker image and inspected bundled code
- Confirmed the error affects multiple server functions (`listEmployees`, `listInvoiceableReports`, `getDistricts`, etc.)
- The issue is intermittent and self-resolves after first request (warm start)
- Both dev and production builds are affected

### Next steps to investigate

- Test with Node.js instead of Bun to isolate if it's Bun-specific
- Check if adding module preloading/warmup before accepting requests helps
- Look for circular imports in the module graph

Would love to hear if anyone has tried running on Node instead of Bun and whether that resolves the issue.

**Comment by juliomuhlbauer** [comment]
I migrated from Bun to Node. The issue has not showed anymore.

**Comment by nicksrandall** [comment]
> I migrated from Bun to Node. The issue has not showed anymore.

I just did this as well, and the issue has gone away. This is a bug in the bun runtime!

**Comment by ulrichstark** [comment]
> This is a bug in the bun runtime!

No, my reproduction doesn't involve Bun.

**Comment by schiller-manuel** [comment]
@nicksrandall  @juliomuhlbauer we need a reproducer that fails on bun but works in node

**Comment by schiller-manuel** [comment]
@ulrichstark  i bumped deps and tried to reproduce, but wasnt able to get this error again.
can you please try again? https://github.com/ulrichstark/tanstack-vite-cannot-access-vite-ssr-import-before-initalization/pull/1

**Comment by ulrichstark** [comment]
> [@ulrichstark](https://github.com/ulrichstark) i bumped deps and tried to reproduce, but wasnt able to get this error again. can you please try again? [ulrichstark/tanstack-vite-cannot-access-vite-ssr-import-before-initalization#1](https://github.com/ulrichstark/tanstack-vite-cannot-access-vite-ssr-import-before-initalization/pull/1)

Yes, you are correct. I [added scripts](https://github.com/ulrichstark/tanstack-vite-cannot-access-vite-ssr-import-before-initalization/commit/c096c0c15290f7ed893cb5d621b7f26709c152e8) to automatically reproduce the issue and to figure out which version fixed it. Running `find-fix-version.sh` four times always returned that [1.142.1](https://github.com/TanStack/router/releases/tag/v1.142.1) (either PR #6159 or #6160) fixed this issue. This also explains why the last relevant comment in this issue is from two weeks ago, because 1.142.1 was released about two weeks ago.

**Comment by zotodev** [comment]
This issue has again come up. I am using 1.145.10

**Comment by schiller-manuel** [comment]
@zotodev please create a new issue including a complete reproducer project

**Comment by juliomuhlbauer** [comment]
This issue is happening on Node runtime too
