### ISSUE TITLE
TanStack Start 1.157.x SSR build uses jsxDEV instead of jsx in production

### ISSUE THREAD

**Issue by mkmrcodes** [tannerlinsley/react-location#6498]
### Which project does this relate to?

Router

### Describe the bug
Production SSR build fails with `TypeError: l.jsxDEV is not a function` when using TanStack Start 1.157.x. The SSR bundle incorrectly uses React's development JSX transform (`jsxDEV`) instead of production (`jsx`).

### Steps to reproduce
1. Create a TanStack Start project with SSR
2. Use `createRouter` with a `Wrap` property containing JSX
3. Build for production: `npm run build`
4. Run production server: `npm run start`
5. Visit the page → 500 error

### Expected behavior
Production build should use `jsx` runtime, not `jsxDEV`

### Environment
- TanStack Start: 1.157.5 (also affects 1.157.0-1.157.4)
- Vite: 7.3.1
- Node: [your version]
- OS: macOS

### Workaround
Works with 1.156.0, or by adding explicit config:
// vite.config.ts
define: {
  'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV || 'production'),
},

### Your Example Website or App

Reproduction: Unable to create StackBlitz reproduction due to SSR/production build requirements.  The issue occurs specifically in production SSR builds with nitro preset. Happy to provide more details or create a GitHub repo if needed.

### Steps to Reproduce the Bug or Issue

Reproduction: Unable to create StackBlitz reproduction due to SSR/production build requirements. 
The issue occurs specifically in production SSR builds with nitro preset.
Happy to provide more details or create a GitHub repo if needed.

### Expected behavior

200

### Platform

- Router / Start Version: [e.g. 1.121.0]
- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Browser Version: [e.g. 91.1]
- Bundler: [e.g. vite]
- Bundler Version: [e.g. 7.0.0]

**Comment by schiller-manuel** [comment]
are you setting NODE_ENV during build?
see https://tanstack.com/start/latest/docs/framework/react/guide/environment-variables#static-node_env-replacement

**Comment by mkmrcodes** [comment]
My bad.
